name: plugin_practice
description: json & realm

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable:
  json_annotation: '>=4.6.0 <4.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

